Fix error when loading Airflow
When the Docker container ran, it executed Airflow, which ran `pip` to check if
the dependencies are installed. However, Airflow's `setup.py` tries to write to
the file `./airflow/git_version` and fails because it has no permission to do
so. This change gives the Airflow user permissions on anything on
$AIRFLOW_HOME.

```
Obtaining airflow[async,celery,crypto,hdfs,hive,jdbc,password,postgres] from git+git://github.com/apache/incubator-airflow.git@35e43f5067f4741640278b765c0e54e4fd45ffa3#egg=airflow[async,password,celery,crypto,postgres,hive,hdfs,jdbc] (fro
m -r /requirements.txt (line 7))
  Skipping because already up-to-date.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/airflow/src/airflow/setup.py", line 304, in <module>
        do_setup()
      File "/usr/local/airflow/src/airflow/setup.py", line 195, in do_setup
        write_version()
      File "/usr/local/airflow/src/airflow/setup.py", line 98, in write_version
        with open(filename, 'w') as a:
    IOError: [Errno 13] Permission denied: 'airflow/git_version'
```